### PR TITLE
Nicer indent ruler

### PR DESCRIPTION
**Pull request by stoivo**

### CODE REVIEW

**Comment by nilium** [comment]
@stoivo Can you provide a screenshot illustrating the difference?

**Comment by stoivo** [comment]
Sorry, my bad
Before 
screen shot 2016-07-02 at 00 09 22
After:
screen shot 2016-07-02 at 00 09 05

**Comment by stoivo** [comment]
and you need this in settings

``` json
"indent_guide_options":[
    "draw_active"
],
```

**Comment by FichteFoll** [comment]
Thanks for the screens.

I'm not a fan of this blue though, although I'll probably try making the caret blue like it is in the console.

I'll add a more prominent `activeGuide` color once I finally find the time to work on this.

**Comment by stoivo** [comment]
Hope you get time to make a nicer indent ruler soon 😄

**Pull request closed without merging**
