### PR TITLE
Add GitGutter plugin colors to themes

### PR DESCRIPTION
**Pull request by mreinhardt**
Background colors don't affect the GitGutter plugin since it's in the gutter, so I added styles to the themes to support coloring of the add/delete/changed symbols.

### CODE REVIEW

**Comment by nilium** [comment]
Would these need to be any different than the current diff deleted/modified/added colors? If not, I might either merge your selectors with theirs or copy the diff colors.

**Comment by mreinhardt** [comment]
It could be merged, but I wasn't sure you'd want to change how diff file viewing behaved. Currently diff file viewing changes the background color of add/mod/del, but for GitGutter only the foreground color can be changed since the symbols appear in the gutter. So if you merge with the standard diff scopes, diff files will have changed foreground instead of background color. (Changing both foreground and background would reduce legibility, obviously.)

Let me know what you want to do and I can go ahead and update the branch accordingly and squash the commit for the pull request.

**Comment by nilium** [comment]
I'll have to look at it to see what exactly GitGutter does.

**Comment by mreinhardt** [comment]
This should give you an idea, this is with my color changes added:

screen shot 2013-10-28 at 3 32 52 pm

First symbol in the gutter indicates a modified line, second symbol indicates lines deleted, and the last two plus symbols are where I added two blank lines.

**Comment by nilium** [comment]
Ok, in that case, reusing the diff selectors doesn't make sense. Merging.

**Pull request merged**
