### PR TITLE
Use the same color (blue) for groups and folders instead of purple

### PR DESCRIPTION
**Pull request by tunix**
This commit changes the color code from purple to blue. When a project is open, purple is really disturbing.

### CODE REVIEW

**Comment by nilium** [comment]
The blue is reserved for active/highlighted things. Same as how orange is reserved for modified things. Purple is the general color already used in Nil and Ayin. Not merging.

**Comment by nilium** [comment]
> purple is really disturbing

Also, what?

**Comment by tunix** [comment]
How about making color configurable via settings?

**Comment by nilium** [comment]
Last I checked, there was no sane way to make color configurable via preferences. Plus you can already override it in an additional theme file, so I don't see a point to adding tons of additional conditional styles to the theme itself.

**Comment by FichteFoll** [comment]
Not that it was supported anyway. I wouldn't have a problem with sane color schemes though, I really hate dem plists.

**Pull request closed without merging**
