### PR TITLE
Fixed a but where modified tabs weren't colored

### PR DESCRIPTION
**Pull request by Grafikart**
On my computer I didn't get the beautifull orange color/indicator so I edited the theme to fix the bug (did not test this on any other computer)

Thanks for your work :)

### CODE REVIEW

**Comment by nilium** [comment]
Not a bug.  Rejected.

**Comment by jeromegn** [comment]
I'm experiencing the same issue.

**Comment by Grafikart** [comment]
When do the orange tab should be visible ?

**Comment by nilium** [comment]
See [issue #1](https://github.com/nilium/st2-nil-theme/issues/1).

**Pull request closed without merging**
